nebula_packages:
    name: nebula-graph-{{ nebula_version }}.{{ os_version }}.{{ arc }}.{{ pkg }}
    version: "{{ nebula_version }}"
    url: https://github.com/vesoft-inc/nebula-graph/releases/download/v{{ nebula_version }}/nebula-graph-{{ nebula_version }}.{{ os_version }}.{{ arc }}.{{ pkg }}
