# The Playbook of Nebula Graph

#- name: deploying prometheus
#  hosts: servers
#  tags:
#    - prometheus
#  roles:
#    - prometheus

#- name: deploying grafana
#  hosts: grafana_servers
#  tags:
#    - grafana
#  roles:
#    - grafana

# deploying Nebula Graph cluster

- name: copy Nebula Graph package to all machines of cluster
  hosts: all
  become: true
  roles: 
    - install

- name: configuration for metad service
  hosts: metad_servers
  become: true
  roles:
    - metad

- name: configuration for graphd service
  hosts: graphd_servers
  become: true
  roles:
    - graphd

- name: configuration for storaged service
  hosts: storaged_servers
  become: true
  roles:
    - storaged

- name: configuration for firewall
  hosts: all
  become: true
  roles:
    - { role: firewalld, when: enable_firewalld is defined and enable_firewalld }
