---
# local preparation on Control Machine

- name: make sure that the Ansible version is Ansible 2.4.2 later, otherwise a compatibility issue occurs
  assert:
    that:
      - ansible_version.full is version('2.5', '>')

- name: create a directory of downloads if it does not exist
  file:
    path: "{{ packages_dir }}"
    state: directory
    mode: 0755

- name: check if the nebula package has existed
  stat: 
    path: "{{ packages_dir }}/{{ nebula_packages.name }}"
  register: stat_result

- name: download nebula graph package
  get_url:
    url: "{{ nebula_packages.url }}"
    dest: "{{ packages_dir }}"
    mode: 0755
  register: get_url_result
  until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
  retries: 2
  when: 
    - force_download or not stat_result.stat.exists
