- name: create directory to store nebula package on all machines in the cluster
  file:
    path: "{{ packages_dir }}"
    state: directory
    mode: 0775

- include_vars: file={{ playbook_dir }}/roles/local/vars/main.yml

- name: copy nebula package from Control Machine to all machines in the cluster
  copy:
    src="{{ packages_dir }}/{{ nebula_packages.name }}"
    dest="{{ packages_dir }}/{{ nebula_packages.name }}"

- name: install nebula package on all machines in the cluster
  package:
    name: "{{ packages_dir }}/{{ nebula_packages.name }}"
    state: present
